import type { ProcessMapConfig } from '@/types/process-map';

// Configuración default del Mapa de Procesos — ISO 9001:2015
// Se usa cuando la organización no tiene config personalizada en Firestore.
// Cada organización puede sobrescribir esto desde organizations/{orgId}/ui_config/process_map

export const DEFAULT_PROCESS_MAP_CONFIG: ProcessMapConfig = {
  levels: [
    {
      level: 1,
      title: 'Dirección',
      color: 'emerald',
      items: [
        {
          processKey: 'planificacion',
          label: 'Planificación y Dirección',
          visible: true,
          applies: true,
          order: 1,
          route: '/planificacion-revision-direccion',
          icon: 'Compass',
        },
        {
          processKey: 'panel_ejecutivo',
          label: 'Panel Ejecutivo',
          visible: true,
          applies: true,
          order: 2,
          route: '/ejecutivo',
          icon: 'BarChart3',
        },
        {
          processKey: 'indicadores',
          label: 'Indicadores y Madurez',
          visible: true,
          applies: true,
          order: 3,
          route: '/maturity',
          icon: 'CheckCircle',
        },
      ],
    },
    {
      level: 2,
      title: 'Control y Mejora',
      color: 'blue',
      items: [
        {
          processKey: 'auditorias',
          label: 'Auditorías',
          visible: true,
          applies: true,
          order: 1,
          route: '/mejoras',
          icon: 'ShieldCheck',
        },
        {
          processKey: 'hallazgos',
          label: 'Hallazgos',
          visible: true,
          applies: true,
          order: 2,
          route: '/mejoras',
          icon: 'AlertTriangle',
        },
        {
          processKey: 'acciones',
          label: 'Acciones Correctivas',
          visible: true,
          applies: true,
          order: 3,
          route: '/mejoras',
          icon: 'Zap',
        },
        {
          processKey: 'partes_interesadas',
          label: 'Partes Interesadas',
          visible: true,
          applies: true,
          order: 4,
          route: '/planificacion-revision-direccion',
          icon: 'Users',
        },
      ],
    },
    {
      level: 3,
      title: 'Procesos de Apoyo',
      color: 'violet',
      items: [
        {
          processKey: 'rrhh',
          label: 'Recursos Humanos',
          visible: true,
          applies: true,
          order: 1,
          route: '/rrhh',
          icon: 'Users',
        },
        {
          processKey: 'documentos',
          label: 'Documentación',
          visible: true,
          applies: true,
          order: 2,
          route: '/documentos',
          icon: 'FileText',
        },
        {
          processKey: 'infraestructura',
          label: 'Infraestructura',
          visible: true,
          applies: true,
          order: 3,
          route: '/iso-infrastructure',
          icon: 'Server',
        },
        {
          processKey: 'diseno_desarrollo',
          label: 'Diseño y Desarrollo',
          visible: true,
          applies: false,
          order: 4,
          route: '/mi-sgc',
          icon: 'Layers',
        },
      ],
    },
    {
      level: 4,
      title: 'Procesos Operativos',
      color: 'amber',
      items: [
        {
          processKey: 'compras',
          label: 'Compras',
          visible: true,
          applies: true,
          order: 1,
          route: '/procesos',
          icon: 'ShoppingCart',
        },
        {
          processKey: 'stock',
          label: 'Stock',
          visible: true,
          applies: true,
          order: 2,
          route: '/dealer/catalogo',
          icon: 'Package',
        },
        {
          processKey: 'repuestos',
          label: 'Repuestos',
          visible: true,
          applies: true,
          order: 3,
          route: '/solicitudes/repuestos',
          icon: 'Wrench',
        },
        {
          processKey: 'servicios',
          label: 'Servicios Técnicos',
          visible: true,
          applies: true,
          order: 4,
          route: '/solicitudes/servicios',
          icon: 'Settings',
        },
        {
          processKey: 'crm_ventas',
          label: 'CRM / Ventas',
          visible: true,
          applies: true,
          order: 5,
          route: '/crm',
          icon: 'Briefcase',
        },
        {
          processKey: 'financiacion',
          label: 'Financiación',
          visible: true,
          applies: true,
          order: 6,
          route: '/gestion-crediticia',
          icon: 'DollarSign',
        },
      ],
    },
  ],
};
