import {
  FunctionalLevel,
  ImplementationMaturity,
  MaturityLevel,
} from '@/types/maturity';

/**
 * Datos de ejemplo para visualizar el Dashboard mientras el Evaluador no esté listo.
 * Estos datos son ficticios y sirven solo para demo.
 */
export const DEMO_MATURITY_DATA: ImplementationMaturity = {
  organizationId: 'demo',
  companySize: 'small',
  globalScore: 47,
  globalLevel: MaturityLevel.CONTROLADO,
  updatedAt: new Date(),

  levels: {
    [FunctionalLevel.LEVEL_1_OPERATION]: {
      level: FunctionalLevel.LEVEL_1_OPERATION,
      score: 65,
      tasks: [
        {
          id: 'op_purchases',
          name: 'Gestión de Compras',
          level: FunctionalLevel.LEVEL_1_OPERATION,
          description: '',
          exists: true,
          evidenceCount: 12,
          score: 70,
        },
        {
          id: 'op_sales',
          name: 'Gestión de Ventas',
          level: FunctionalLevel.LEVEL_1_OPERATION,
          description: '',
          exists: true,
          evidenceCount: 25,
          score: 85,
        },
        {
          id: 'op_stock',
          name: 'Control de Stock',
          level: FunctionalLevel.LEVEL_1_OPERATION,
          description: '',
          exists: true,
          evidenceCount: 5,
          score: 50,
        },
        {
          id: 'op_production',
          name: 'Producción',
          level: FunctionalLevel.LEVEL_1_OPERATION,
          description: '',
          exists: false,
          evidenceCount: 0,
          score: 0,
        },
        {
          id: 'op_logistics',
          name: 'Logística',
          level: FunctionalLevel.LEVEL_1_OPERATION,
          description: '',
          exists: true,
          evidenceCount: 8,
          score: 60,
        },
      ],
    },
    [FunctionalLevel.LEVEL_2_SUPPORT]: {
      level: FunctionalLevel.LEVEL_2_SUPPORT,
      score: 45,
      tasks: [
        {
          id: 'sup_hr',
          name: 'RRHH',
          level: FunctionalLevel.LEVEL_2_SUPPORT,
          description: '',
          exists: true,
          evidenceCount: 6,
          score: 55,
        },
        {
          id: 'sup_training',
          name: 'Capacitación',
          level: FunctionalLevel.LEVEL_2_SUPPORT,
          description: '',
          exists: true,
          evidenceCount: 3,
          score: 40,
        },
        {
          id: 'sup_maintenance',
          name: 'Mantenimiento',
          level: FunctionalLevel.LEVEL_2_SUPPORT,
          description: '',
          exists: false,
          evidenceCount: 0,
          score: 0,
        },
        {
          id: 'sup_docs',
          name: 'Documentación',
          level: FunctionalLevel.LEVEL_2_SUPPORT,
          description: '',
          exists: true,
          evidenceCount: 20,
          score: 75,
        },
        {
          id: 'sup_it',
          name: 'Sistemas IT',
          level: FunctionalLevel.LEVEL_2_SUPPORT,
          description: '',
          exists: true,
          evidenceCount: 2,
          score: 30,
        },
      ],
    },
    [FunctionalLevel.LEVEL_3_CONTROL]: {
      level: FunctionalLevel.LEVEL_3_CONTROL,
      score: 35,
      tasks: [
        {
          id: 'ctrl_audit',
          name: 'Auditorías',
          level: FunctionalLevel.LEVEL_3_CONTROL,
          description: '',
          exists: true,
          evidenceCount: 2,
          score: 45,
        },
        {
          id: 'ctrl_nconformance',
          name: 'No Conformidades',
          level: FunctionalLevel.LEVEL_3_CONTROL,
          description: '',
          exists: true,
          evidenceCount: 4,
          score: 50,
        },
        {
          id: 'ctrl_customer_sat',
          name: 'Satisfacción Cliente',
          level: FunctionalLevel.LEVEL_3_CONTROL,
          description: '',
          exists: false,
          evidenceCount: 0,
          score: 0,
        },
        {
          id: 'ctrl_kpi',
          name: 'Indicadores',
          level: FunctionalLevel.LEVEL_3_CONTROL,
          description: '',
          exists: true,
          evidenceCount: 1,
          score: 25,
        },
      ],
    },
    [FunctionalLevel.LEVEL_4_DIRECTION]: {
      level: FunctionalLevel.LEVEL_4_DIRECTION,
      score: 20,
      tasks: [
        {
          id: 'dir_context',
          name: 'Contexto Org.',
          level: FunctionalLevel.LEVEL_4_DIRECTION,
          description: '',
          exists: true,
          evidenceCount: 1,
          score: 35,
        },
        {
          id: 'dir_planning',
          name: 'Planificación',
          level: FunctionalLevel.LEVEL_4_DIRECTION,
          description: '',
          exists: false,
          evidenceCount: 0,
          score: 0,
        },
        {
          id: 'dir_review',
          name: 'Revisión Dirección',
          level: FunctionalLevel.LEVEL_4_DIRECTION,
          description: '',
          exists: false,
          evidenceCount: 0,
          score: 0,
        },
        {
          id: 'dir_risk',
          name: 'Gestión Riesgos',
          level: FunctionalLevel.LEVEL_4_DIRECTION,
          description: '',
          exists: true,
          evidenceCount: 2,
          score: 40,
        },
      ],
    },
  },

  nextSteps: [
    {
      id: 'demo_1',
      title: 'Ejecutar primera auditoría del año',
      description: 'No hay auditorías registradas en los últimos 6 meses.',
      priority: 'high',
      impactLevel: FunctionalLevel.LEVEL_3_CONTROL,
      actionUrl: '/auditorias',
    },
    {
      id: 'demo_2',
      title: 'Completar planificación estratégica',
      description: 'El módulo de planificación está vacío.',
      priority: 'high',
      impactLevel: FunctionalLevel.LEVEL_4_DIRECTION,
      actionUrl: '/planificacion-revision-direccion',
    },
    {
      id: 'demo_3',
      title: 'Registrar encuestas de satisfacción',
      description: 'No hay encuestas de clientes cargadas.',
      priority: 'medium',
      impactLevel: FunctionalLevel.LEVEL_3_CONTROL,
      actionUrl: '/dashboard/satisfaccion-partes',
    },
  ],
};
