/**
 * Script de Seed: Datos de Prueba para Dashboard de Agentes
 *
 * Genera jobs ficticios en diferentes estados para visualizar el dashboard.
 * Uso: npx ts-node scripts/seed-dummy-jobs.ts <ORG_ID>
 */

import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';

// Configuración básica de Firebase
const serviceAccount = require('../../serviceAccountKey.json');

if (!process.env.FIREBASE_PROJECT_ID) {
  initializeApp({
    credential: cert(serviceAccount),
  });
}

const db = getFirestore();

async function main() {
  const args = process.argv.slice(2);
  const organizationId = args[0];

  if (!organizationId) {
    console.error('⚠️  Por favor, proporcione un Organization ID.');
    console.error('Uso: npx ts-node scripts/seed-dummy-jobs.ts <ORG_ID>');
    process.exit(1);
  }

  console.log(`=== SEED: Dummy Agent Jobs ===`);
  console.log(`Organización: ${organizationId}`);

  const jobs = [
    {
      intent: 'crm.contact.create',
      status: 'completed',
      priority: 'normal',
      agent: 'agent_sales_01',
      user: 'user_dummy_1',
      result: { contact_id: 'ct_123', status: 'created' },
      duration: 1200, // ms
    },
    {
      intent: 'iso.audit.generate',
      status: 'running',
      priority: 'high',
      agent: 'agent_governance_01',
      user: 'user_dummy_admin',
      duration: 0,
    },
    {
      intent: 'whatsapp.message.send',
      status: 'failed',
      priority: 'critical',
      agent: 'agent_worker_01',
      user: 'user_dummy_1',
      error: { code: 'network_error', message: 'Timeout connecting to Twilio' },
      duration: 5000,
    },
    {
      intent: 'erp.invoice.sync',
      status: 'queued',
      priority: 'low',
      agent: 'agent_finance_01',
      user: 'user_dummy_2',
      duration: 0,
    },
    {
      intent: 'iso.compliance.check',
      status: 'completed',
      priority: 'normal',
      agent: 'agent_governance_01',
      user: 'user_dummy_admin',
      result: { score: 85, compliance: true },
      duration: 3500,
    },
  ];

  const batch = db.batch();
  const collectionRef = db.collection('agent_jobs');

  for (const job of jobs) {
    const docRef = collectionRef.doc();

    // Calcular timestamps
    const now = new Date();
    const created = new Date(now.getTime() - Math.random() * 86400000); // Últimas 24h
    let started = null;
    let completed = null;

    if (
      job.status === 'running' ||
      job.status === 'completed' ||
      job.status === 'failed'
    ) {
      started = new Date(created.getTime() + 1000);
    }

    if (job.status === 'completed' || job.status === 'failed') {
      completed = new Date(started!.getTime() + (job.duration || 1000));
    }

    batch.set(docRef, {
      organization_id: organizationId,
      user_id: job.user,
      agent_instance_id: job.agent,
      intent: job.intent,
      payload: { dummy: true, description: 'Generated by seed script' },
      status: job.status,
      priority: job.priority,
      result: job.result || null,
      error: job.error || null,
      created_at: Timestamp.fromDate(created),
      updated_at: Timestamp.fromDate(new Date()),
      started_at: started ? Timestamp.fromDate(started) : null,
      completed_at: completed ? Timestamp.fromDate(completed) : null,
      attempts: job.status === 'failed' ? 3 : 1,
      max_attempts: 3,
    });
  }

  await batch.commit();
  console.log(`✅ ${jobs.length} jobs insertados correctamente.`);
  console.log('Ahora puede visitar /mcp/dashboard para ver los datos.');
}

main().catch(console.error);
