/**
 * Fix: limpia subcollections incorrectas e inserta en colecciones top-level correctas.
 *
 * Colecciones correctas (según los Services del app):
 *   departments      → top-level, filtro organization_id
 *   positions        → top-level, filtro organization_id
 *   personnel        → top-level, filtro organization_id
 *   processDefinitions → top-level, filtro organization_id
 *
 * Uso:
 *   npx ts-node --project tsconfig.scripts.json scripts/seed-agrobiciufa-fix.ts
 */

import { cert, getApps, initializeApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import * as fs from 'fs';
import * as path from 'path';

const ORG_ID = 'org_agrobiciufa';

function initAdmin() {
  if (getApps().length > 0) return;
  const serviceAccountPath = path.resolve(process.cwd(), 'service-account.json');
  const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'));
  initializeApp({ credential: cert(serviceAccount) });
  console.log(`📦 Firebase Admin — proyecto: ${serviceAccount.project_id}`);
}

function now() { return Timestamp.now(); }
function ts(date: Date) { return Timestamp.fromDate(date); }

// ─── Limpiar subcollections incorrectas ──────────────────────────────────────
async function cleanSubcollection(db: ReturnType<typeof getFirestore>, subcol: string) {
  const snap = await db.collection('organizations').doc(ORG_ID).collection(subcol).get();
  if (snap.empty) { console.log(`  (ya vacía: ${subcol})`); return 0; }
  const batch = db.batch();
  snap.docs.forEach(d => batch.delete(d.ref));
  await batch.commit();
  console.log(`  🗑️  Eliminados ${snap.docs.length} docs de organizations/${ORG_ID}/${subcol}`);
  return snap.docs.length;
}

// ─── DEPARTAMENTOS ────────────────────────────────────────────────────────────
const DEPARTAMENTOS = [
  { id: 'dept_agro_direccion', nombre: 'Dirección General', descripcion: 'Conducción estratégica de la empresa, toma de decisiones de alto nivel y representación institucional ante CNH/CASE IH.', is_active: true },
  { id: 'dept_agro_ventas', nombre: 'Ventas y Comercial', descripcion: 'Venta de maquinaria agrícola nueva y usada (tractores, cosechadoras, sembradoras, pulverizadoras CASE IH). Atención a clientes, seguimiento de oportunidades y financiación.', is_active: true },
  { id: 'dept_agro_repuestos', nombre: 'Repuestos', descripcion: 'Venta y gestión de repuestos originales CASE IH. Mostrador, cotizaciones, pedidos al distribuidor y control de stock de repuestos.', is_active: true },
  { id: 'dept_agro_servicios', nombre: 'Servicios Técnicos', descripcion: 'Taller de reparación y mantenimiento de maquinaria agrícola CASE IH. Gestión de órdenes de trabajo, garantías y servicio en campo.', is_active: true },
  { id: 'dept_agro_calidad', nombre: 'Calidad', descripcion: 'Sistema de Gestión de Calidad ISO 9001. Auditorías internas, control de documentos, gestión de no conformidades y mejora continua.', is_active: true },
  { id: 'dept_agro_compras', nombre: 'Compras y Abastecimiento', descripcion: 'Gestión de compras de repuestos, insumos y servicios. Evaluación y homologación de proveedores. Negociación con CNH y distribuidores.', is_active: true },
  { id: 'dept_agro_almacenes', nombre: 'Almacenes e Inventario', descripcion: 'Control de stock de repuestos y maquinaria. Ingreso y egreso de mercadería. Inventarios periódicos y gestión del depósito.', is_active: true },
  { id: 'dept_agro_admin', nombre: 'Administración y Finanzas', descripcion: 'Contabilidad, tesorería, facturación, cuentas a pagar y cobrar. Liquidación de sueldos y cumplimiento impositivo.', is_active: true },
];

// ─── PUESTOS ─────────────────────────────────────────────────────────────────
const PUESTOS = [
  { id: 'puesto_agro_gerente_general', nombre: 'Gerente General', descripcion_responsabilidades: 'Conducción integral de la empresa. Define objetivos estratégicos, reporta a los accionistas y es interlocutor principal con CNH Industrial Argentina.', requisitos_experiencia: '10+ años en concesionarios o industria agropecuaria', requisitos_formacion: 'Licenciatura en Administración, Ingeniería Agronómica o MBA', departamento_id: 'dept_agro_direccion', nivel: 'gerencial', is_active: true },
  { id: 'puesto_agro_gerente_ventas', nombre: 'Gerente de Ventas', descripcion_responsabilidades: 'Liderazgo del equipo comercial. Define cuotas, estrategias de venta, manejo de la relación con clientes clave y coordinación con CASE IH para asignación de unidades.', requisitos_experiencia: '5+ años en ventas de maquinaria agrícola o equipos industriales', requisitos_formacion: 'Licenciatura en Administración, Agronomía o Ingeniería', departamento_id: 'dept_agro_ventas', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'gerencial', is_active: true },
  { id: 'puesto_agro_asesor_comercial_sr', nombre: 'Asesor Comercial Senior', descripcion_responsabilidades: 'Gestión de cuentas clave: grandes productores, contratistas y cooperativas. Venta de maquinaria nueva y usada, armado de propuestas con financiación.', requisitos_experiencia: '4-6 años en venta de maquinaria o agro', requisitos_formacion: 'Técnico o Licenciatura en Agro, Adm o afín', departamento_id: 'dept_agro_ventas', reporta_a_id: 'puesto_agro_gerente_ventas', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_asesor_comercial', nombre: 'Asesor Comercial', descripcion_responsabilidades: 'Prospección y atención de clientes, visitas a campo, cotizaciones y seguimiento de oportunidades en el CRM.', requisitos_experiencia: '1-3 años en ventas. Preferible sector agro.', requisitos_formacion: 'Técnico en Ventas, Administración o carrera afín', departamento_id: 'dept_agro_ventas', reporta_a_id: 'puesto_agro_gerente_ventas', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_coordinador_postventa', nombre: 'Coordinador de Postventa', descripcion_responsabilidades: 'Seguimiento post-entrega de unidades. Encuestas de satisfacción, gestión de garantías en coordinación con Servicios, y retención de clientes.', requisitos_experiencia: '2-4 años en atención al cliente o postventa', requisitos_formacion: 'Técnico o Licenciatura en Administración', departamento_id: 'dept_agro_ventas', reporta_a_id: 'puesto_agro_gerente_ventas', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_gerente_repuestos', nombre: 'Gerente de Repuestos', descripcion_responsabilidades: 'Gestión del área de repuestos: stock, pedidos a CNH, precios, atención a taller y clientes. Define política de inventario y metas de venta del área.', requisitos_experiencia: '5+ años en repuestos de maquinaria agrícola o automotriz', requisitos_formacion: 'Técnico mecánico o Licenciatura en Logística/Adm', departamento_id: 'dept_agro_repuestos', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'gerencial', is_active: true },
  { id: 'puesto_agro_vendedor_repuestos', nombre: 'Vendedor de Repuestos (Mostrador)', descripcion_responsabilidades: 'Atención en mostrador, identificación de repuestos en catálogos CASE, cotizaciones, facturación y coordinación con almacenes para la entrega.', requisitos_experiencia: '1-3 años en repuestos de maquinaria o automotriz', requisitos_formacion: 'Secundario técnico o Técnico en Mecánica', departamento_id: 'dept_agro_repuestos', reporta_a_id: 'puesto_agro_gerente_repuestos', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_repositor_repuestos', nombre: 'Repositor de Repuestos', descripcion_responsabilidades: 'Ingreso y control de mercadería de repuestos, organización del depósito, preparación de pedidos para mostrador y taller.', requisitos_experiencia: 'Sin experiencia previa requerida', requisitos_formacion: 'Secundario completo', departamento_id: 'dept_agro_repuestos', reporta_a_id: 'puesto_agro_gerente_repuestos', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_gerente_servicios', nombre: 'Gerente de Servicios', descripcion_responsabilidades: 'Conducción del taller. Define capacidad, asigna recursos, gestiona garantías CASE, planifica capacitaciones técnicas y mide KPIs del área.', requisitos_experiencia: '7+ años en taller de maquinaria, preferible CASE/CNH', requisitos_formacion: 'Ingeniería Mecánica o Técnico Superior en Mecánica/Electrónica', departamento_id: 'dept_agro_servicios', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'gerencial', is_active: true },
  { id: 'puesto_agro_jefe_taller', nombre: 'Jefe de Taller', descripcion_responsabilidades: 'Supervisión diaria del taller. Apertura y seguimiento de órdenes de trabajo, asignación de técnicos, control de tiempos y calidad de las reparaciones.', requisitos_experiencia: '4-6 años en taller de maquinaria agrícola', requisitos_formacion: 'Técnico en Mecánica o Electrónica', departamento_id: 'dept_agro_servicios', reporta_a_id: 'puesto_agro_gerente_servicios', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_tecnico_especialista', nombre: 'Técnico Especialista CASE', descripcion_responsabilidades: 'Diagnóstico y reparación de sistemas complejos (electrónica, hidráulica, AFS/Precision Farming). Realiza servicio en campo y atención de garantías.', requisitos_experiencia: '5+ años en maquinaria CASE IH o CNH. Certificación CNH requerida.', requisitos_formacion: 'Técnico en Mecánica, Electrónica o Mecatrónica', departamento_id: 'dept_agro_servicios', reporta_a_id: 'puesto_agro_jefe_taller', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_tecnico_mecanico', nombre: 'Técnico Mecánico', descripcion_responsabilidades: 'Mantenimiento preventivo y reparaciones generales de maquinaria agrícola (motor, transmisión, sistema hidráulico).', requisitos_experiencia: '2-4 años en taller mecánico', requisitos_formacion: 'Técnico en Mecánica o Técnico Agropecuario', departamento_id: 'dept_agro_servicios', reporta_a_id: 'puesto_agro_jefe_taller', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_recepcionista_ot', nombre: 'Recepcionista de Órdenes de Trabajo', descripcion_responsabilidades: 'Recepción de maquinaria en taller, apertura de OT, comunicación con clientes sobre estado de los trabajos y coordinación de turnos de servicio.', requisitos_experiencia: '1-2 años en atención al cliente o administración', requisitos_formacion: 'Secundario completo. Deseable Técnico en Administración.', departamento_id: 'dept_agro_servicios', reporta_a_id: 'puesto_agro_jefe_taller', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_responsable_calidad', nombre: 'Responsable de Calidad (ISO 9001)', descripcion_responsabilidades: 'Implementación y mantenimiento del SGC ISO 9001. Realiza auditorías internas, gestiona no conformidades, acciones correctivas y coordina la revisión por la dirección.', requisitos_experiencia: '4+ años en sistemas de gestión de calidad', requisitos_formacion: 'Licenciatura en Calidad, Ingeniería o afín. Auditor interno ISO 9001.', departamento_id: 'dept_agro_calidad', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_jefe_compras', nombre: 'Jefe de Compras', descripcion_responsabilidades: 'Gestión de compras de repuestos, insumos y servicios. Negociación con proveedores nacionales e internacionales. Homologación de proveedores según ISO 9001.', requisitos_experiencia: '4+ años en compras industriales o agro', requisitos_formacion: 'Licenciatura en Administración, Logística o Ingeniería', departamento_id: 'dept_agro_compras', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_comprador', nombre: 'Comprador', descripcion_responsabilidades: 'Emisión de órdenes de compra, seguimiento de pedidos, recepción administrativa de mercadería y actualización del sistema de stock.', requisitos_experiencia: '1-3 años en compras o administración', requisitos_formacion: 'Técnico en Administración o Logística', departamento_id: 'dept_agro_compras', reporta_a_id: 'puesto_agro_jefe_compras', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_jefe_almacen', nombre: 'Jefe de Almacén', descripcion_responsabilidades: 'Control integral del depósito: ingresos, egresos, inventarios cíclicos y anuales, organización del espacio y cumplimiento de procedimientos de almacenamiento.', requisitos_experiencia: '3-5 años en almacenes o depósitos industriales', requisitos_formacion: 'Técnico en Logística o Administración', departamento_id: 'dept_agro_almacenes', reporta_a_id: 'puesto_agro_jefe_compras', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_operario_deposito', nombre: 'Operario de Depósito', descripcion_responsabilidades: 'Recepción física de mercadería, ubicación en racks, preparación de pedidos para el mostrador y el taller, y manejo de equipo de elevación.', requisitos_experiencia: 'Sin experiencia previa. Se capacita en puesto.', requisitos_formacion: 'Secundario completo. Licencia de conducir autoelevador (deseable).', departamento_id: 'dept_agro_almacenes', reporta_a_id: 'puesto_agro_jefe_almacen', nivel: 'operativo', is_active: true },
  { id: 'puesto_agro_administrador', nombre: 'Administrador General', descripcion_responsabilidades: 'Supervisión de contabilidad, tesorería, liquidación de sueldos y cumplimiento impositivo. Reporta resultados financieros a la Dirección.', requisitos_experiencia: '5+ años en administración contable-financiera', requisitos_formacion: 'Contador Público o Licenciatura en Administración', departamento_id: 'dept_agro_admin', reporta_a_id: 'puesto_agro_gerente_general', nivel: 'gerencial', is_active: true },
  { id: 'puesto_agro_contador', nombre: 'Contador', descripcion_responsabilidades: 'Registración contable, liquidación de impuestos (IVA, Ganancias, Ingresos Brutos), cuentas a pagar y cobrar, y cierre mensual.', requisitos_experiencia: '2-4 años en estudio contable o empresa', requisitos_formacion: 'Contador Público (matrícula activa)', departamento_id: 'dept_agro_admin', reporta_a_id: 'puesto_agro_administrador', nivel: 'tecnico', is_active: true },
  { id: 'puesto_agro_cajero', nombre: 'Cajero / Tesorero', descripcion_responsabilidades: 'Manejo de caja chica, cobranzas de mostrador, pagos a proveedores, conciliación bancaria y archivo de comprobantes.', requisitos_experiencia: '1-2 años en tesorería o caja', requisitos_formacion: 'Técnico en Administración', departamento_id: 'dept_agro_admin', reporta_a_id: 'puesto_agro_administrador', nivel: 'operativo', is_active: true },
];

// ─── PERSONAL ─────────────────────────────────────────────────────────────────
const PERSONAL = [
  { id: 'per_agro_001', nombres: 'Héctor Domingo', apellidos: 'Bicicchi', email: 'hector.bicicchi@agrobiciufa.com.ar', telefono: '+543492415001', documento_identidad: '14500123', fecha_nacimiento: ts(new Date('1968-04-10')), nacionalidad: 'Argentina', direccion: 'Sargento Cabral 345, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2005-03-01')), numero_legajo: 'AB-001', estado: 'Activo', tipo_personal: 'gerencial', puesto_id: 'puesto_agro_gerente_general', departamento_id: 'dept_agro_direccion', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true },
  { id: 'per_agro_002', nombres: 'Gustavo Andrés', apellidos: 'Maiocchi', email: 'gustavo.maiocchi@agrobiciufa.com.ar', telefono: '+543492415002', documento_identidad: '20881344', fecha_nacimiento: ts(new Date('1978-09-22')), nacionalidad: 'Argentina', direccion: 'Av. Italia 1200, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2011-01-15')), numero_legajo: 'AB-002', estado: 'Activo', tipo_personal: 'gerencial', puesto_id: 'puesto_agro_gerente_ventas', departamento_id: 'dept_agro_ventas', meta_mensual: 3000000, comision_porcentaje: 1.5, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
  { id: 'per_agro_003', nombres: 'Marcelo Fabián', apellidos: 'Bertolini', email: 'marcelo.bertolini@agrobiciufa.com.ar', telefono: '+543492415003', documento_identidad: '24112567', fecha_nacimiento: ts(new Date('1982-03-15')), nacionalidad: 'Argentina', direccion: 'Bv. Lehmann 890, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2013-06-01')), numero_legajo: 'AB-003', estado: 'Activo', tipo_personal: 'ventas', puesto_id: 'puesto_agro_asesor_comercial_sr', departamento_id: 'dept_agro_ventas', meta_mensual: 2500000, comision_porcentaje: 2, tiene_acceso_sistema: true, zona_venta: 'Zona Norte — Sunchales / Gálvez', supervisor_id: 'per_agro_002' },
  { id: 'per_agro_004', nombres: 'Nicolás Ezequiel', apellidos: 'Ravenna', email: 'nicolas.ravenna@agrobiciufa.com.ar', telefono: '+543492415004', documento_identidad: '32540089', fecha_nacimiento: ts(new Date('1991-11-28')), nacionalidad: 'Argentina', direccion: 'Pellegrini 230, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2018-08-01')), numero_legajo: 'AB-004', estado: 'Activo', tipo_personal: 'ventas', puesto_id: 'puesto_agro_asesor_comercial', departamento_id: 'dept_agro_ventas', meta_mensual: 1500000, comision_porcentaje: 1.8, tiene_acceso_sistema: true, zona_venta: 'Zona Sur — Esperanza / San Justo', supervisor_id: 'per_agro_002' },
  { id: 'per_agro_005', nombres: 'Florencia Belén', apellidos: 'Garello', email: 'florencia.garello@agrobiciufa.com.ar', telefono: '+543492415005', documento_identidad: '34890112', fecha_nacimiento: ts(new Date('1993-07-04')), nacionalidad: 'Argentina', direccion: 'Roque Sáenz Peña 780, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2020-03-01')), numero_legajo: 'AB-005', estado: 'Activo', tipo_personal: 'ventas', puesto_id: 'puesto_agro_asesor_comercial', departamento_id: 'dept_agro_ventas', meta_mensual: 1500000, comision_porcentaje: 1.8, tiene_acceso_sistema: true, zona_venta: 'Zona Central — Rafaela', supervisor_id: 'per_agro_002' },
  { id: 'per_agro_006', nombres: 'Valeria Gisela', apellidos: 'Cantù', email: 'valeria.cantu@agrobiciufa.com.ar', telefono: '+543492415006', documento_identidad: '30120456', fecha_nacimiento: ts(new Date('1988-02-18')), nacionalidad: 'Argentina', direccion: 'Moreno 455, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2016-05-01')), numero_legajo: 'AB-006', estado: 'Activo', tipo_personal: 'administrativo', puesto_id: 'puesto_agro_coordinador_postventa', departamento_id: 'dept_agro_ventas', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_002' },
  { id: 'per_agro_007', nombres: 'Roberto Oscar', apellidos: 'Faraldo', email: 'roberto.faraldo@agrobiciufa.com.ar', telefono: '+543492415007', documento_identidad: '18770234', fecha_nacimiento: ts(new Date('1972-06-30')), nacionalidad: 'Argentina', direccion: 'Chacabuco 1100, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2008-09-01')), numero_legajo: 'AB-007', estado: 'Activo', tipo_personal: 'gerencial', puesto_id: 'puesto_agro_gerente_repuestos', departamento_id: 'dept_agro_repuestos', meta_mensual: 800000, comision_porcentaje: 1, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
  { id: 'per_agro_008', nombres: 'Diego Ariel', apellidos: 'Ghezzi', email: 'diego.ghezzi@agrobiciufa.com.ar', telefono: '+543492415008', documento_identidad: '28330567', fecha_nacimiento: ts(new Date('1986-12-05')), nacionalidad: 'Argentina', direccion: 'España 990, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2014-02-01')), numero_legajo: 'AB-008', estado: 'Activo', tipo_personal: 'ventas', puesto_id: 'puesto_agro_vendedor_repuestos', departamento_id: 'dept_agro_repuestos', meta_mensual: 400000, comision_porcentaje: 0.8, tiene_acceso_sistema: true, supervisor_id: 'per_agro_007' },
  { id: 'per_agro_009', nombres: 'Lautaro Sebastián', apellidos: 'Porrini', email: 'lautaro.porrini@agrobiciufa.com.ar', telefono: '+543492415009', documento_identidad: '40220789', fecha_nacimiento: ts(new Date('1998-05-12')), nacionalidad: 'Argentina', direccion: 'San Lorenzo 340, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2022-04-01')), numero_legajo: 'AB-009', estado: 'Activo', tipo_personal: 'administrativo', puesto_id: 'puesto_agro_repositor_repuestos', departamento_id: 'dept_agro_repuestos', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: false, supervisor_id: 'per_agro_007' },
  { id: 'per_agro_010', nombres: 'Jorge Alfredo', apellidos: 'Zanetta', email: 'jorge.zanetta@agrobiciufa.com.ar', telefono: '+543492415010', documento_identidad: '16990344', fecha_nacimiento: ts(new Date('1970-01-20')), nacionalidad: 'Argentina', direccion: 'Lavalle 670, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2007-07-01')), numero_legajo: 'AB-010', estado: 'Activo', tipo_personal: 'gerencial', puesto_id: 'puesto_agro_gerente_servicios', departamento_id: 'dept_agro_servicios', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
  { id: 'per_agro_011', nombres: 'Pablo Daniel', apellidos: 'Taselli', email: 'pablo.taselli@agrobiciufa.com.ar', telefono: '+543492415011', documento_identidad: '22440678', fecha_nacimiento: ts(new Date('1980-08-14')), nacionalidad: 'Argentina', direccion: 'San Martín 1230, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2010-03-01')), numero_legajo: 'AB-011', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_jefe_taller', departamento_id: 'dept_agro_servicios', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_010' },
  { id: 'per_agro_012', nombres: 'Fernando Luis', apellidos: 'Bonansea', email: 'fernando.bonansea@agrobiciufa.com.ar', telefono: '+543492415012', documento_identidad: '25660901', fecha_nacimiento: ts(new Date('1984-04-25')), nacionalidad: 'Argentina', direccion: 'Colón 450, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2012-01-01')), numero_legajo: 'AB-012', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_tecnico_especialista', departamento_id: 'dept_agro_servicios', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_011' },
  { id: 'per_agro_013', nombres: 'Mauro Ezequiel', apellidos: 'Rosciani', email: 'mauro.rosciani@agrobiciufa.com.ar', telefono: '+543492415013', documento_identidad: '35110234', fecha_nacimiento: ts(new Date('1994-10-09')), nacionalidad: 'Argentina', direccion: 'Mitre 780, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2019-01-15')), numero_legajo: 'AB-013', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_tecnico_mecanico', departamento_id: 'dept_agro_servicios', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: false, supervisor_id: 'per_agro_011' },
  { id: 'per_agro_014', nombres: 'Brenda Soledad', apellidos: 'Parisi', email: 'brenda.parisi@agrobiciufa.com.ar', telefono: '+543492415014', documento_identidad: '38990567', fecha_nacimiento: ts(new Date('1997-03-30')), nacionalidad: 'Argentina', direccion: 'Córdoba 310, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2021-09-01')), numero_legajo: 'AB-014', estado: 'Activo', tipo_personal: 'administrativo', puesto_id: 'puesto_agro_recepcionista_ot', departamento_id: 'dept_agro_servicios', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_011' },
  { id: 'per_agro_015', nombres: 'Claudia Beatriz', apellidos: 'Volpato', email: 'claudia.volpato@agrobiciufa.com.ar', telefono: '+543492415015', documento_identidad: '22100890', fecha_nacimiento: ts(new Date('1980-11-15')), nacionalidad: 'Argentina', direccion: 'Bv. Santa Fe 1560, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2015-03-01')), numero_legajo: 'AB-015', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_responsable_calidad', departamento_id: 'dept_agro_calidad', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
  { id: 'per_agro_016', nombres: 'Ariel Marcelo', apellidos: 'Pagliaro', email: 'ariel.pagliaro@agrobiciufa.com.ar', telefono: '+543492415016', documento_identidad: '21880123', fecha_nacimiento: ts(new Date('1979-07-22')), nacionalidad: 'Argentina', direccion: 'Sarmiento 900, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2009-05-01')), numero_legajo: 'AB-016', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_jefe_compras', departamento_id: 'dept_agro_compras', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
  { id: 'per_agro_017', nombres: 'Jimena Rocío', apellidos: 'Ferrero', email: 'jimena.ferrero@agrobiciufa.com.ar', telefono: '+543492415017', documento_identidad: '36550456', fecha_nacimiento: ts(new Date('1995-09-08')), nacionalidad: 'Argentina', direccion: 'Independencia 550, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2021-04-01')), numero_legajo: 'AB-017', estado: 'Activo', tipo_personal: 'administrativo', puesto_id: 'puesto_agro_comprador', departamento_id: 'dept_agro_compras', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_016' },
  { id: 'per_agro_018', nombres: 'Luis Alberto', apellidos: 'Tosello', email: 'luis.tosello@agrobiciufa.com.ar', telefono: '+543492415018', documento_identidad: '19770789', fecha_nacimiento: ts(new Date('1974-12-03')), nacionalidad: 'Argentina', direccion: 'Av. 9 de Julio 1800, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2010-08-01')), numero_legajo: 'AB-018', estado: 'Activo', tipo_personal: 'técnico', puesto_id: 'puesto_agro_jefe_almacen', departamento_id: 'dept_agro_almacenes', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_016' },
  { id: 'per_agro_019', nombres: 'Agustín Leandro', apellidos: 'Pistarino', email: 'agustin.pistarino@agrobiciufa.com.ar', telefono: '+543492415019', documento_identidad: '42110012', fecha_nacimiento: ts(new Date('2000-02-17')), nacionalidad: 'Argentina', direccion: 'Tucumán 660, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2023-03-01')), numero_legajo: 'AB-019', estado: 'Activo', tipo_personal: 'administrativo', puesto_id: 'puesto_agro_operario_deposito', departamento_id: 'dept_agro_almacenes', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: false, supervisor_id: 'per_agro_018' },
  { id: 'per_agro_020', nombres: 'María Cristina', apellidos: 'Bellora', email: 'cristina.bellora@agrobiciufa.com.ar', telefono: '+543492415020', documento_identidad: '17440345', fecha_nacimiento: ts(new Date('1971-05-25')), nacionalidad: 'Argentina', direccion: 'Alberdi 1340, Rafaela, Santa Fe', fecha_contratacion: ts(new Date('2006-02-01')), numero_legajo: 'AB-020', estado: 'Activo', tipo_personal: 'gerencial', puesto_id: 'puesto_agro_administrador', departamento_id: 'dept_agro_admin', meta_mensual: 0, comision_porcentaje: 0, tiene_acceso_sistema: true, supervisor_id: 'per_agro_001' },
];

// ─── PROCESOS ─────────────────────────────────────────────────────────────────
const PROCESOS = [
  { id: 'pro_agro_ven_001', codigo: 'PRO-VEN-001', nombre: 'Venta de Maquinaria Nueva y Usada', objetivo: 'Gestionar el ciclo completo de venta de maquinaria agrícola CASE IH, asegurando la satisfacción del cliente, el cumplimiento de los objetivos comerciales y el correcto registro en el sistema.', alcance: 'Abarca desde la prospección o contacto inicial del cliente hasta la entrega de la unidad y la generación del expediente de venta.', responsable: 'Gerente de Ventas', departamento_responsable_id: 'dept_agro_ventas', departamento_responsable_nombre: 'Ventas y Comercial', entradas: ['Consulta de cliente (presencial, telefónica, web)', 'Catálogo y lista de precios CASE IH vigente', 'Stock de unidades disponibles', 'Condiciones de financiación'], salidas: ['Propuesta comercial firmada', 'Contrato de compraventa', 'Remito de entrega y factura', 'Expediente de venta completo'], controles: ['Verificación de datos fiscales del cliente', 'Aprobación de descuentos por Gerente', 'Revisión de usados por Servicios antes de aceptar'], indicadores: ['Unidades vendidas por período', 'Facturación mensual', 'Tiempo promedio de ciclo de venta (días)', 'Tasa de conversión (%)'], documentos: ['DOC-VEN-01: Formulario de cotización', 'DOC-VEN-02: Contrato de compraventa', 'DOC-VEN-03: Protocolo de entrega'], estado: 'activo' },
  { id: 'pro_agro_rep_001', codigo: 'PRO-REP-001', nombre: 'Gestión y Venta de Repuestos', objetivo: 'Garantizar la disponibilidad de repuestos originales CASE IH para clientes y taller, optimizando el stock y minimizando los tiempos de espera.', alcance: 'Incluye atención en mostrador, identificación de repuestos en catálogos CNH, cotización, pedido al distribuidor, recepción y entrega.', responsable: 'Gerente de Repuestos', departamento_responsable_id: 'dept_agro_repuestos', departamento_responsable_nombre: 'Repuestos', entradas: ['Solicitud de cliente (mostrador o telefónica)', 'Pedido interno de taller (OT activa)', 'Catálogo de repuestos CASE IH', 'Stock disponible en almacén'], salidas: ['Repuesto entregado con remito', 'Factura de venta', 'Pedido de reposición al distribuidor', 'Actualización de inventario'], controles: ['Verificación de número de parte', 'Control de precios contra lista vigente CNH', 'Registro de movimientos en sistema'], indicadores: ['Facturación mensual de repuestos', 'Fill rate (%)', 'Tiempo de atención en mostrador (min)', 'Rotación de inventario'], documentos: ['DOC-REP-01: Identificación de repuestos', 'DOC-REP-02: Política de pedidos a distribuidor', 'DOC-REP-03: Procedimiento de devoluciones'], estado: 'activo' },
  { id: 'pro_agro_ser_001', codigo: 'PRO-SER-001', nombre: 'Servicio Técnico y Reparaciones', objetivo: 'Brindar servicio de mantenimiento y reparación de maquinaria agrícola CASE IH con calidad, eficiencia y seguridad.', alcance: 'Aplica a todas las órdenes de trabajo (OT) gestionadas en el taller, incluyendo servicios en campo.', responsable: 'Gerente de Servicios', departamento_responsable_id: 'dept_agro_servicios', departamento_responsable_nombre: 'Servicios Técnicos', entradas: ['Solicitud de servicio del cliente', 'Unidad ingresada al taller con descripción de falla', 'Historial de servicio de la unidad (CNH)', 'Repuestos disponibles en almacén'], salidas: ['Orden de Trabajo completa', 'Maquinaria reparada y probada', 'Factura de mano de obra y repuestos', 'Informe de diagnóstico al cliente'], controles: ['Diagnóstico previo obligatorio', 'Aprobación del presupuesto por el cliente', 'Prueba funcional antes de entrega', 'Revisión de calidad por Jefe de Taller'], indicadores: ['OT completadas por mes', 'Tiempo promedio de reparación (hs)', 'Facturación de mano de obra', 'Índice de retrabajo (%)'], documentos: ['DOC-SER-01: Recepción de unidad', 'DOC-SER-02: Apertura y cierre de OT', 'DOC-SER-03: Prueba funcional pre-entrega'], estado: 'activo' },
  { id: 'pro_agro_gar_001', codigo: 'PRO-GAR-001', nombre: 'Gestión de Garantías CASE IH', objetivo: 'Gestionar eficientemente las reclamaciones de garantía, asegurando el cumplimiento de los procedimientos CNH y la recuperación del costo.', alcance: 'Aplica a toda unidad CASE IH en período de garantía según condiciones del fabricante.', responsable: 'Gerente de Servicios', departamento_responsable_id: 'dept_agro_servicios', departamento_responsable_nombre: 'Servicios Técnicos', entradas: ['Reclamo de garantía del cliente', 'Manual de garantías CASE IH vigente', 'Sistema de garantías CNH (portal web)', 'Historial de la unidad'], salidas: ['Garantía aprobada o rechazada por CNH', 'Reparación ejecutada y documentada', 'Recupero de costos acreditado por CNH'], controles: ['Verificación de vigencia de garantía', 'Fotografías y evidencia documentadas', 'Aprobación de CNH antes de iniciar reparación'], indicadores: ['Garantías procesadas por mes', 'Tasa de aprobación CNH (%)', 'Tiempo promedio de resolución (días)', 'Monto recuperado ($/mes)'], documentos: ['DOC-GAR-01: Apertura de garantía CNH', 'DOC-GAR-02: Documentación requerida', 'DOC-GAR-03: Comunicación al cliente'], estado: 'activo' },
  { id: 'pro_agro_com_001', codigo: 'PRO-COM-001', nombre: 'Gestión de Compras y Proveedores', objetivo: 'Asegurar el abastecimiento oportuno de repuestos, insumos y servicios a través de un proceso de compras eficiente con proveedores evaluados.', alcance: 'Aplica a todas las compras realizadas por la empresa. Incluye la evaluación y re-evaluación periódica de proveedores.', responsable: 'Jefe de Compras', departamento_responsable_id: 'dept_agro_compras', departamento_responsable_nombre: 'Compras y Abastecimiento', entradas: ['Solicitud de compra interna', 'Stock mínimo alertado por Almacenes', 'Lista de proveedores homologados', 'Presupuestos de proveedores'], salidas: ['Orden de Compra emitida y firmada', 'Mercadería recibida y conforme', 'Proveedor evaluado', 'Registro de compra en sistema'], controles: ['Mínimo 2 presupuestos para compras >$500.000', 'Aprobación de Gerencia para compras >$2.000.000', 'Solo comprar a proveedores homologados'], indicadores: ['Tiempo promedio de proceso de compra (días)', 'Cumplimiento de plazos de proveedores (%)', 'Ahorro por negociación ($/mes)', 'Proveedores evaluados (%)'], documentos: ['DOC-COM-01: Solicitud y aprobación de compras', 'DOC-COM-02: Evaluación de proveedores', 'DOC-COM-03: Registro de proveedores homologados'], estado: 'activo' },
  { id: 'pro_agro_alm_001', codigo: 'PRO-ALM-001', nombre: 'Control de Almacenes e Inventario', objetivo: 'Mantener un registro preciso y actualizado del inventario, asegurando la disponibilidad de los materiales y minimizando pérdidas por obsolescencia.', alcance: 'Aplica al depósito de repuestos y al área de maquinaria. Incluye ingresos, egresos, inventarios cíclicos e inventario general anual.', responsable: 'Jefe de Almacén', departamento_responsable_id: 'dept_agro_almacenes', departamento_responsable_nombre: 'Almacenes e Inventario', entradas: ['Mercadería recibida de compras', 'Devoluciones de taller o mostrador', 'Solicitudes de retiro de repuestos'], salidas: ['Mercadería entregada con remito', 'Inventario actualizado', 'Informe de inventario cíclico mensual', 'Alerta de stock mínimo'], controles: ['Toda entrada/salida registrada el mismo día', 'Inventario cíclico mensual', 'Inventario general anual', 'Identificación de obsoletos >12 meses sin movimiento'], indicadores: ['Exactitud del inventario (%)', 'Diferencias en inventario cíclico ($)', 'Rotación de inventario (veces/año)', 'Valor total del inventario ($)'], documentos: ['DOC-ALM-01: Recepción y ubicación de mercadería', 'DOC-ALM-02: Retiro de mercadería', 'DOC-ALM-03: Inventario cíclico'], estado: 'activo' },
  { id: 'pro_agro_cal_001', codigo: 'PRO-CAL-001', nombre: 'Auditoría Interna ISO 9001', objetivo: 'Verificar periódicamente que el SGC de Agro Bicufa cumple con ISO 9001:2015 y se implementa y mantiene eficazmente.', alcance: 'Aplica a todos los procesos del SGC. Auditorías planificadas al menos una vez por año.', responsable: 'Responsable de Calidad (ISO 9001)', departamento_responsable_id: 'dept_agro_calidad', departamento_responsable_nombre: 'Calidad', entradas: ['Programa anual de auditorías', 'Norma ISO 9001:2015', 'Documentación del SGC', 'Resultados de auditorías anteriores'], salidas: ['Informe de auditoría con hallazgos', 'No Conformidades documentadas', 'Plan de acciones correctivas', 'Registro para revisión por la dirección'], controles: ['Auditores no pueden auditar su propia área', 'Comunicación con 15 días de anticipación', 'Seguimiento de cierre de NC en plazo'], indicadores: ['Auditorías realizadas vs programadas (%)', 'NC detectadas por auditoría', '% NC cerradas en plazo', 'Tiempo promedio de cierre de NC (días)'], documentos: ['DOC-CAL-01: Programa anual de auditorías', 'DOC-CAL-02: Plan de auditoría', 'DOC-CAL-03: Lista de verificación', 'DOC-CAL-04: Informe de auditoría', 'DOC-CAL-05: Formulario de NC y acción correctiva'], estado: 'activo' },
  { id: 'pro_agro_pos_001', codigo: 'PRO-POS-001', nombre: 'Postventa y Satisfacción del Cliente', objetivo: 'Medir y mejorar continuamente la satisfacción de los clientes mediante seguimiento post-venta/servicio, gestión de reclamos y mejoras basadas en feedback.', alcance: 'Aplica a todos los clientes que realizaron una compra o recibieron un servicio técnico en los últimos 90 días.', responsable: 'Coordinador de Postventa', departamento_responsable_id: 'dept_agro_ventas', departamento_responsable_nombre: 'Ventas y Comercial', entradas: ['Listado de entregas y servicios completados', 'Reclamos recibidos por cualquier canal', 'Resultados de encuestas NPS anteriores'], salidas: ['Encuesta NPS enviada y resultado registrado', 'Reclamo gestionado y resuelto', 'Informe mensual de satisfacción para Dirección'], controles: ['Encuesta NPS enviada en 72hs de entrega/servicio', 'Reclamos respondidos en máximo 24hs hábiles', 'Escalado a Gerente General para NPS < 6'], indicadores: ['NPS mensual', 'Tasa de respuesta a encuestas NPS (%)', 'Tiempo promedio de resolución de reclamos (hs)', 'Retención de clientes (%)'], documentos: ['DOC-POS-01: Encuesta NPS post-entrega', 'DOC-POS-02: Gestión de reclamos', 'DOC-POS-03: Informe mensual de satisfacción'], estado: 'activo' },
];

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n🚀 Seed Agro Bicufa — FIX: colecciones top-level correctas\n');
  initAdmin();
  const db = getFirestore();

  // 1. Limpiar subcollections incorrectas
  console.log('🧹 Limpiando subcollections incorrectas...');
  await cleanSubcollection(db, 'departments');
  await cleanSubcollection(db, 'positions');
  await cleanSubcollection(db, 'personnel');
  await cleanSubcollection(db, 'processes');

  // 2. Insertar en colecciones top-level correctas
  console.log('\n📁 Insertando departamentos en top-level...');
  {
    const batch = db.batch();
    for (const d of DEPARTAMENTOS) {
      batch.set(db.collection('departments').doc(d.id), { ...d, organization_id: ORG_ID, created_at: now(), updated_at: now() }, { merge: true });
      console.log(`  → ${d.nombre}`);
    }
    await batch.commit();
    console.log(`✅ ${DEPARTAMENTOS.length} departamentos`);
  }

  console.log('\n👔 Insertando puestos en top-level...');
  {
    const batch = db.batch();
    for (const p of PUESTOS) {
      batch.set(db.collection('positions').doc(p.id), { ...p, organization_id: ORG_ID, created_at: now(), updated_at: now() }, { merge: true });
      console.log(`  → ${p.nombre}`);
    }
    await batch.commit();
    console.log(`✅ ${PUESTOS.length} puestos`);
  }

  console.log('\n👥 Insertando personal en top-level...');
  {
    for (let i = 0; i < PERSONAL.length; i += 10) {
      const batch = db.batch();
      const chunk = PERSONAL.slice(i, i + 10);
      for (const p of chunk) {
        batch.set(db.collection('personnel').doc(p.id), { ...p, organization_id: ORG_ID, created_at: now(), updated_at: now() }, { merge: true });
        console.log(`  → [${p.numero_legajo}] ${p.nombres} ${p.apellidos}`);
      }
      await batch.commit();
    }
    console.log(`✅ ${PERSONAL.length} empleados`);
  }

  console.log('\n⚙️  Insertando procesos en top-level (processDefinitions)...');
  {
    const batch = db.batch();
    for (const p of PROCESOS) {
      batch.set(db.collection('processDefinitions').doc(p.id), { ...p, organization_id: ORG_ID, createdAt: now(), updatedAt: now() }, { merge: true });
      console.log(`  → [${p.codigo}] ${p.nombre}`);
    }
    await batch.commit();
    console.log(`✅ ${PROCESOS.length} procesos`);
  }

  console.log('\n🎉 ¡Todo listo! Colecciones insertadas:');
  console.log('   departments       → 8 docs');
  console.log('   positions         → 21 docs');
  console.log('   personnel         → 20 docs');
  console.log('   processDefinitions → 8 docs');
  console.log('\n   Recargá el panel y deberías ver todo.\n');
  process.exit(0);
}

main().catch(e => { console.error('❌', e); process.exit(1); });
